In [1]:
import pandas as pd
import sys
import os

sys.path.append(os.path.abspath("../src"))

In [2]:
labeled_df = pd.read_csv('../data/labeledTrainData.tsv.zip', header=0, delimiter="\t", quoting=3)
labeled_df.describe()

         sentiment
count  25000.00000
mean       0.50000
std        0.50001
min        0.00000
25%        0.00000
50%        0.50000
75%        1.00000
max        1.00000

In [3]:
labeled_df.head(10)

          id  sentiment                                             review
0   "5814_8"          1  "With all this stuff going down at the moment ...
1   "2381_9"          1  "\"The Classic War of the Worlds\" by Timothy ...
2   "7759_3"          0  "The film starts with a manager (Nicholas Bell...
3   "3630_4"          0  "It must be assumed that those who praised thi...
4   "9495_8"          1  "Superbly trashy and wondrously unpretentious ...
5   "8196_8"          1  "I dont know why people think this is such a b...
6   "7166_2"          0  "This movie could have been very good, but com...
7  "10633_1"          0  "I watched this video at a friend's house. I'm...
8    "319_1"          0  "A friend of mine bought this film for £1, and...
9  "8713_10"          1  "<br /><br />This movie is full of references....

In [4]:
unlabeled_df = pd.read_csv('../data/unlabeledTrainData.tsv.zip', header=0, delimiter="\t", quoting=3)
unlabeled_df.describe()

              id                                             review
count      50000                                              50000
unique     50000                                              49507
top     "7379_0"  "Am not from America, I usually watch this sho...
freq           1                                                  5

In [5]:
unlabeled_df.head(10)

# release the memory
del unlabeled_df

In [6]:
# import re
# from nltk.corpus import stopwords

# @pd.api.extensions.register_series_accessor("nlp")
# class KaggleWord2VecAccessor:
#     def __init__(self, series):
#         self._s = series        
#         self._stopwords = set(stopwords.words("english"))

#     def review_to_wordlist(self):    
#         return self._s.apply(self._review_to_wordlist)

#     def _review_to_wordlist(self, text):
#         stripper = HTMLStripper()
#         stripper.feed(text)

#         # 1. Remove HTML
#         review_text = stripper.get_text()

#         # 2. Remove non-letters
#         review_text = re.sub("[^a-zA-Z]"," ", review_text)

#         # 3. Convert words to lower case and split them
#         words = review_text.lower().split()

#         # 4. Optionally remove stop words (false by default)
#         # if remove_stopwords:
#         #     stops = set(stopwords.words("english"))
#         words = [w for w in words if w not in self._stopwords]

#         return words

In [9]:

import my_utils # noqa: F401

test1 = labeled_df.review[:10].nlp.review_to_wordlist()
test1

0    [stuff, going, moment, mj, started, listening,...
1    [classic, war, worlds, timothy, hines, enterta...
2    [film, starts, manager, nicholas, bell, giving...
3    [must, assumed, praised, film, greatest, filme...
4    [superbly, trashy, wondrously, unpretentious, ...
5    [dont, know, people, think, bad, movie, got, p...
6    [movie, could, good, comes, way, short, cheesy...
7    [watched, video, friend, house, glad, waste, m...
8    [friend, mine, bought, film, even, grossly, ov...
9    [movie, full, references, like, mad, max, ii, ...
Name: review, dtype: object